### ISSUE TITLE
A small bug in BufferPoolManager::FetchPageImpl step1.1

### ISSUE THREAD

**Issue by gaofanfei** [duynguyen-ori75/bustub-2019#3]
```cpp
  if (iterator != page_table_.end()) {
    // page_id found
    replacer_->Pin(iterator->second);
    return GetPages() + iterator->second;
  }
```
I think we should increase the page->pin_count_ . 
Suppose there are multiple threads requesting the same page, and this page is already in the buffer pool, we should increase page->pin_count_ to represent that this page is Pinned by those threads.

**Comment by duynguyen-ori75** [comment]
Probably you're right. Could you write a test and create a pull req for this case?

I have been too busy recently.
